// Generated by CoffeeScript 1.8.0

/*
	stylus-boilerplate

	camelize.coffee

	@author Sean

	@note Created on 2014-08-28 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */


/*
	Stylus helper for "camelizing" a string
	@see http://stackoverflow.com/questions/25477795/stylus-generate-camelcase-variable
	@example
		to-uppercase("mystring") => "MYSTRING"
 */

(function() {
  if (typeof module !== "undefined" && module !== null) {
    module.exports = function() {
      return function(stylus) {
        return stylus.define("to-upper-case", function(node) {
          var nodeName, val;
          nodeName = node.nodeName;
          val = node.string;
          if (nodeName === "string") {
            return new stylus.nodes.String(val.toUpperCase());
          } else if (nodeName === "ident") {
            return new stylus.nodes.Ident(val.toUpperCase());
          } else {
            throw new Error("to-upper-case accepts string or ident but got " + nodeName);
          }
        });
      };
    };
  }

}).call(this);

//# sourceMappingURL=camelize.js.map
