// Generated by CoffeeScript 1.7.1

/*
	stylus-boilerplate

	test.coffee

	@author Sean

	@note Created on 2014-08-29 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  describe("stylus boilerplate", function() {
    return it("should have some unit tests", function() {
      return assert("but it doesn't", "but it doesn't");
    });
  });

}).call(this);

//# sourceMappingURL=test.map
