// Generated by CoffeeScript 1.7.1

/*
	stylus-boilerplate

	main.coffee

	@author Sean

	@note Created on 2014-08-23 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  "use strict";
  jQuery(document).ready(function() {
    return console.log("Ready for action");
  });

}).call(this);

//# sourceMappingURL=main.map
